### ISSUE TITLE
[Bug] Can not start with rc "no such file or directory"

### ISSUE THREAD

**Issue by mka-2016** [trusz/rapid-compose#4]
After I run "rc" this appears:

> panic: open /Users/myUserName/.rapid-compose: no such file or directory
> 
> goroutine 1 [running]:
> github.com/trusz/rapid-compose/src/storage.readFile(0xc000090000, 0x21, 0x39, 0xc00009fea0, 0x10cd4f6)
> 	/Users/trusz/Work/rapid-compose/src/storage/storage.go:48 +0x83
> github.com/trusz/rapid-compose/src/storage.Read(0x0, 0xc00009fee8, 0x10cf23f)
> 	/Users/trusz/Work/rapid-compose/src/storage/storage.go:22 +0x3d
> github.com/trusz/rapid-compose/src/persist.LoadSelections(0x11cc76a, 0x1, 0x0)
> 	/Users/trusz/Work/rapid-compose/src/persist/persist.go:35 +0x26
> main.main()
> 	/Users/trusz/Work/rapid-compose/src/rc/main.go:28 +0xd1

**Comment by trusz** [comment]
Resolved with: 210ffcf
Version: [v1.3.1](https://github.com/trusz/rapid-compose/releases/tag/v1.3.1)
